#!/usr/bin/env python3

import hashlib
import json
import os
import pathlib
import re
import stat
import sys
import time


ARTIFACT_FIELDS = {
    "schema",
    "schema_version",
    "producer_git_sha",
    "producer_dirty",
    "inputs",
    "inputs_sha256",
    "test_mutation",
    "user_data",
    "service_unit",
    "service_env",
    "persisted_node_json",
}
REQUIRED_INPUTS = {
    "api_key",
    "browser_origin",
    "caddy_runtime",
    "customer_id",
    "customer_profile",
    "db_url",
    "engine_profile",
    "environment",
    "node_id",
    "provider",
    "region",
    "secret_delivery",
}
FIXED_IDENTITY = {
    "provider": "aws",
    "customer_profile": "paid_beta_v6",
    "secret_delivery": "aws_ssm",
    "customer_id": "00000000-0000-0000-0000-000000000000",
    "node_id": "node-managed-startup-proof",
    "environment": "test",
}
OWNED_SERVICE_DIRECTIVES = ("WorkingDirectory", "EnvironmentFile", "ExecStart")
OWNED_SERVICE_VALUES = (
    "/var/lib/flapjack",
    "/etc/flapjack/env",
    "/usr/local/bin/flapjack",
)


def read_artifact(artifact_path: pathlib.Path) -> tuple[bytes, str, dict]:
    if not os.path.lexists(artifact_path):
        raise SystemExit("generated artifact must exist")
    metadata = artifact_path.lstat()
    if not stat.S_ISREG(metadata.st_mode):
        raise SystemExit("generated artifact must be a regular file")
    if stat.S_IMODE(metadata.st_mode) != 0o600:
        raise SystemExit("generated artifact mode must be 0600")
    artifact_bytes = artifact_path.read_bytes()
    artifact_digest = hashlib.sha256(artifact_bytes).hexdigest()
    pause_after_read_for_immutability_test()
    try:
        artifact = json.loads(artifact_bytes)
    except (UnicodeDecodeError, json.JSONDecodeError) as error:
        raise SystemExit(f"generated artifact must be valid UTF-8 JSON: {error}")
    return artifact_bytes, artifact_digest, artifact


def pause_after_read_for_immutability_test() -> None:
    pause_path_raw = os.environ.get("MANAGED_FLEET_HA_CONSUMER_TEST_PAUSE_AFTER_READ")
    if not pause_path_raw:
        return
    pause_path = pathlib.Path(pause_path_raw)
    ready_path = pause_path.with_suffix(".ready")
    release_path = pause_path.with_suffix(".release")
    ready_path.touch(exist_ok=False)
    for _ in range(1_000):
        if release_path.exists():
            return
        time.sleep(0.005)
    raise SystemExit("generated artifact test synchronization timed out")


def validate_artifact(artifact: object, expected_sha: str, expected_mutation: str) -> dict:
    if not isinstance(artifact, dict) or set(artifact) != ARTIFACT_FIELDS:
        raise SystemExit("generated artifact fields do not match schema v1")
    if (
        artifact["schema"] != "fjcloud_managed_startup_fixture"
        or type(artifact["schema_version"]) is not int
        or artifact["schema_version"] != 1
    ):
        raise SystemExit("generated artifact schema/version mismatch")
    if (
        not isinstance(artifact["producer_git_sha"], str)
        or artifact["producer_git_sha"] != expected_sha
        or not re.fullmatch(r"[0-9a-f]{40}", expected_sha)
    ):
        raise SystemExit("generated artifact producer identity mismatch")
    if artifact["producer_dirty"] is not False:
        raise SystemExit("generated artifact producer must be clean")
    validate_artifact_value_types(artifact)
    validate_mutation(artifact, expected_mutation)
    validate_inputs(artifact)
    validate_service_unit(artifact["service_unit"])
    return artifact


def validate_artifact_value_types(artifact: dict) -> None:
    for field in ("inputs_sha256", "user_data", "service_unit", "service_env"):
        if not isinstance(artifact[field], str):
            raise SystemExit(f"generated artifact {field} must be a string")
    persisted = artifact["persisted_node_json"]
    if persisted is not None and not isinstance(persisted, (dict, str)):
        raise SystemExit("generated artifact persisted_node_json type must be object, string, or null")
    if not artifact["user_data"] or not artifact["service_env"].endswith("\n"):
        raise SystemExit("generated artifact text fields must preserve generated bytes")


def validate_mutation(artifact: dict, expected_mutation: str) -> None:
    mutation = None if expected_mutation == "baseline" else expected_mutation
    if mutation not in {None, "bootstrap", "advertise"} or artifact["test_mutation"] != mutation:
        raise SystemExit("generated artifact mutation label mismatch")


def validate_inputs(artifact: dict) -> None:
    inputs = artifact["inputs"]
    valid_shape = (
        isinstance(inputs, dict)
        and set(inputs) == REQUIRED_INPUTS
        and all(isinstance(value, str) for value in inputs.values())
    )
    if not valid_shape:
        raise SystemExit("generated artifact inputs do not match the corrected fixed case")
    if any(inputs.get(name) != value for name, value in FIXED_IDENTITY.items()):
        raise SystemExit("generated artifact inputs are outside AWS/paid_beta_v6/aws_ssm fixed identity")
    canonical_inputs = json.dumps(inputs, sort_keys=True, separators=(",", ":")).encode()
    if artifact["inputs_sha256"] != hashlib.sha256(canonical_inputs).hexdigest():
        raise SystemExit("generated artifact inputs_sha256 mismatch")


def validate_service_unit(service_unit: str) -> None:
    section = None
    owned = {name: [] for name in OWNED_SERVICE_DIRECTIVES}
    for raw_line in service_unit.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("[") and line.endswith("]"):
            section = line[1:-1]
            continue
        key, separator, value = line.partition("=")
        if not separator:
            raise SystemExit("malformed service unit directive")
        if key in owned:
            if section != "Service":
                raise SystemExit(f"service unit {key} must be owned by Service")
            owned[key].append(value)
        unsupported = key == "Environment" or key.startswith("Root")
        unsupported = unsupported or key.startswith("ExecStart") and key != "ExecStart"
        if section == "Service" and unsupported:
            raise SystemExit(f"unsupported service ownership directive: {key}")
    for key, values in owned.items():
        if len(values) != 1:
            raise SystemExit(f"service unit must contain exactly one {key}")
    observed_values = tuple(owned[name][0] for name in OWNED_SERVICE_DIRECTIVES)
    if observed_values != OWNED_SERVICE_VALUES:
        raise SystemExit("service unit ownership paths do not match the managed contract")


def materialize_fixture(artifact: dict, mapped_root_raw: str) -> dict:
    if ".." in pathlib.PurePath(mapped_root_raw).parts:
        raise SystemExit("mapped fixture root must not contain parent traversal")
    mapped_root = pathlib.Path(mapped_root_raw)
    if mapped_root.exists() or not mapped_root.is_absolute():
        raise SystemExit("mapped fixture root must be an absolute nonexistent path")
    mapped_root.mkdir(mode=0o700, parents=False)
    service_root = mapped_root / "service"
    service_root.mkdir(mode=0o700)
    (service_root / "flapjack.service").write_text(artifact["service_unit"], encoding="utf-8")
    (service_root / "flapjack.env").write_text(artifact["service_env"], encoding="utf-8")
    fixture_files = {
        "service/flapjack.service": artifact["service_unit"],
        "service/flapjack.env": artifact["service_env"],
    }
    persisted = artifact["persisted_node_json"]
    if persisted is not None:
        fixture_files["service/data/node.json"] = (
            persisted
            if isinstance(persisted, str)
            else json.dumps(persisted, sort_keys=True, separators=(",", ":")) + "\n"
        )
    return {
        "working_directory": str(service_root),
        "environment_file": str(service_root / "flapjack.env"),
        "fixture": {
            "expected_outcome": "loaded",
            "resolved_data_directory": "service/data",
            "environment": {},
            "files": fixture_files,
        },
    }


def main() -> None:
    artifact_path = pathlib.Path(sys.argv[1])
    expected_sha, expected_mutation, mapped_root_raw = sys.argv[2:5]
    before, artifact_digest, artifact = read_artifact(artifact_path)
    validated_artifact = validate_artifact(artifact, expected_sha, expected_mutation)
    result = materialize_fixture(validated_artifact, mapped_root_raw)
    if artifact_path.read_bytes() != before:
        raise SystemExit("generated artifact changed during consumption")
    result["artifact_sha256"] = artifact_digest
    result["producer_git_sha"] = expected_sha
    print(json.dumps(result, sort_keys=True, separators=(",", ":")))


if __name__ == "__main__":
    main()
