#!/usr/bin/env bash

# Public synthetic artifact construction and mutation helpers for the managed
# startup consumer contract. The sourcing harness owns assertions and cleanup.

write_valid_generated_artifact() {
  local artifact="$1"
  local producer_sha="$2"

  python3 - "$artifact" "$producer_sha" <<'PY'
import hashlib
import json
import os
import sys

path, producer_sha = sys.argv[1:]
inputs = {
    "api_key": "managed-startup-proof-key",
    "browser_origin": "https://cloud.example.invalid",
    "caddy_runtime": "available",
    "customer_id": "00000000-0000-0000-0000-000000000000",
    "customer_profile": "paid_beta_v6",
    "db_url": "postgres://fixture:fixture@127.0.0.1:1/fjcloud",
    "engine_profile": "paid_beta_v5",
    "environment": "test",
    "node_id": "node-managed-startup-proof",
    "provider": "aws",
    "region": "eu-central-1",
    "secret_delivery": "aws_ssm",
}
compact = json.dumps(inputs, sort_keys=True, separators=(",", ":")).encode()
artifact = {
    "schema": "fjcloud_managed_startup_fixture",
    "schema_version": 1,
    "producer_git_sha": producer_sha,
    "producer_dirty": False,
    "inputs": inputs,
    "inputs_sha256": hashlib.sha256(compact).hexdigest(),
    "test_mutation": None,
    "user_data": "synthetic generated bytes\n",
    "service_unit": "[Unit]\nDescription=fixture\n\n[Service]\nWorkingDirectory=/var/lib/flapjack\nEnvironmentFile=/etc/flapjack/env\nExecStart=/usr/local/bin/flapjack\n\n[Install]\nWantedBy=multi-user.target\n",
    "service_env": "# generated\n\nFLAPJACK_NODE_ID=node-managed-startup-proof\nFLAPJACK_BIND_ADDR=127.0.0.1:7700\nFLAPJACK_ADMIN_KEY=managed-startup-proof-key\nFLAPJACK_BROWSER_ORIGIN='https://cloud.example.invalid'\n",
    "persisted_node_json": None,
}
fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
with os.fdopen(fd, "w", encoding="utf-8") as output:
    json.dump(artifact, output, sort_keys=True, separators=(",", ":"))
PY
}

mutate_generated_artifact() {
  local artifact="$1"
  local case_name="$2"

  python3 - "$artifact" "$case_name" <<'PY'
import json
import sys

path, case = sys.argv[1:]
artifact = json.load(open(path, encoding="utf-8"))
if case == "partial-output":
    del artifact["user_data"]
elif case == "persisted-node-type":
    artifact["persisted_node_json"] = True
elif case == "schema-type":
    artifact["schema_version"] = True
elif case == "stale-producer":
    artifact["producer_git_sha"] = "2" * 40
elif case == "dirty-producer":
    artifact["producer_dirty"] = True
elif case == "wrong-mutation":
    artifact["test_mutation"] = "advertise"
elif case == "digest-mismatch":
    artifact["inputs_sha256"] = "0" * 64
elif case == "wrong-provider":
    artifact["inputs"]["provider"] = "hetzner"
elif case == "duplicate-working-directory":
    artifact["service_unit"] = artifact["service_unit"].replace("WorkingDirectory=/var/lib/flapjack\n", "WorkingDirectory=/var/lib/flapjack\nWorkingDirectory=/tmp\n")
elif case == "missing-working-directory":
    artifact["service_unit"] = artifact["service_unit"].replace("WorkingDirectory=/var/lib/flapjack\n", "")
elif case == "extra-environment-import":
    artifact["service_unit"] = artifact["service_unit"].replace("EnvironmentFile=/etc/flapjack/env\n", "EnvironmentFile=/etc/flapjack/env\nEnvironmentFile=/tmp/extra\n")
elif case == "duplicate-exec-start":
    artifact["service_unit"] = artifact["service_unit"].replace("ExecStart=/usr/local/bin/flapjack\n", "ExecStart=/usr/local/bin/flapjack\nExecStart=/usr/local/bin/flapjack\n")
elif case == "malformed-service-directive":
    artifact["service_unit"] = artifact["service_unit"].replace("ExecStart=/usr/local/bin/flapjack\n", "MalformedDirective\nExecStart=/usr/local/bin/flapjack\n")
elif case == "exec-arguments":
    artifact["service_unit"] = artifact["service_unit"].replace("ExecStart=/usr/local/bin/flapjack\n", "ExecStart=/usr/local/bin/flapjack --auto-port\n")
elif case == "root-override":
    artifact["service_unit"] = artifact["service_unit"].replace("ExecStart=", "RootDirectory=/tmp/root\nExecStart=")
elif case == "unsupported-env-syntax":
    artifact["service_env"] += "UNSAFE=$HOME\n"
elif case == "duplicate-env":
    artifact["service_env"] += "FLAPJACK_NODE_ID=duplicate\n"
with open(path, "w", encoding="utf-8") as output:
    json.dump(artifact, output, sort_keys=True, separators=(",", ":"))
PY
}
